---
name: 'helm-action'
description: 'xxxx'
inputs:
  kube_config:
    description: 'Kubeconfig yaml contents.'
    required: true
  release:
    description: 'Helm release name. You can use env vars here.'
    required: true
  namespace:
    description: 'Namespace to deploy to. You can use env vars here.'
    required: true
  chart:
    description: 'Helm chart path.'
    required: true
  kube_context:
    description: 'Context to use if there are multiple.'
    required: false
  values_file:
    description: 'Helm values file path.'
    required: false
  stubify_vars:
    description: 'Env vars to stubify. Will create a domain-valid version if the var.'
    required: false
  atomic:
    description: 'Adds --atomic flag to helm'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
