---
name: 'helm-action'
description: 'Does Helm stuff'
inputs:
  kube_config:
    description: 'Kubeconfig yaml contents.'
    required: true
  kube_context:
    description: 'Context to use if there are multiple.'
    required: false
  debug:
    description: 'Spams debug messages. Might contain sensitive data.'
    required: false
  stubify_vars:
    description: 'Env vars to stubify. Will create a domain-valid version if the var.'
    required: false
  helm_release:
    description: 'Helm release name. You can use env vars here.'
    required: true
  helm_chart:
    description: 'Helm chart path.'
    required: false
  helm_namespace:
    description: 'Namespace to deploy to. You can use env vars here.'
    required: true
  helm_values_file:
    description: 'Helm values file path.'
    required: false
  helm_atomic:
    description: 'Adds --atomic flag to helm.'
    required: false
  helm_wait:
    description: 'Adds --wait flag to helm.'
    required: false
  helm_timeout:
    description: 'Adds --timeout XXs flag to helm.'
    required: false
  tail:
    description: 'Will try tailing pod logs during deployment.'
    required: false
  tail_selector:
    description: 'kubectl selector to use for tailing pods. Required when tail=true.'
    required: false
  tail_until:
    description: 'Will stop tailing when it finds the sepcified string. Required when tail=true.'
    required: false
  tail_timeout:
    description: 'How long to try tailing for.'
    required: false
  rollout:
    description: 'Will do a kubectl rollout status --wait'
    required: false
  rollout_deployment:
    description: 'the deployment to track'
    required: false
  rollout_timeout:
    description: 'How long to wait for rollout'
    required: false
  uninstall:
    description: 'Makes this action uninstall a helm release'
    required: false
  delete_namespace:
    description: 'Will delete the namespace provided.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
